baseURL       = "/"
languageCode  = "en-sg"
title         = "Bethany Christian Centre"
summarylength = 25

# Site Params
[params]
  dateFormat = "2 AUG 2024"
  description = "A Pentecostal Assemblies of God church"

  [params.cta_activities]
    title       = "New to Bethany?"
    description = """\
      Discover what is going on and find something suitable for you!\
      """
    buttonText  = "Find out more"
    buttonUrl   = "/activities/"

  [params.contactInfo]
    name    = "Bethany Christian Centre"
    address = "167 Yio Chu Kang Road, Singapore 545620"
    phone   = "+65 6285 7151"
    email   = "hello@bcc.org.sg"

[services]
  [services.googleAnalytics]
    id = 'G-5H8V3KQ6XZ'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false      
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
        
[module]
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
